version: 2

models:
  - name: trips_av_sc_processed
    description: "Processed trips data with trip durations, waiting times, and time slots for Avondale to Sagrada Cantina routes"
    columns:
      - name: stop_id
        description: "Identifier for the stop"
        type: string
        tests:
          - not_null
      
      - name: trip_id
        description: "Unique identifier for the trip"
        type: string
        tests:
          - not_null
      
      - name: route_id
        description: "Identifier for the route"
        type: string
        tests:
          - not_null
      
      - name: stop_name
        description: "Name of the stop from stops_consolidated table"
        type: string
        tests:
          - not_null
      
      - name: trip_start_time
        description: "Start time of the trip"
        type: string
        tests:
          - not_null
      
      - name: service_date
        description: "Parsed service_date as date type"
        type: date
        tests:
          - not_null
      
      - name: start_datetime
        description: "Combined datetime of service_date and arrival_time"
        type: datetime
        tests:
          - not_null
      
      - name: arrival_datetime
        description: "Final destination arrival datetime for the trip"
        type: datetime
        tests:
          - not_null
      
      - name: trip_duration
        description: "Duration of the trip in minutes"
        type: integer
        tests:
          - not_null
      
      - name: trip_duration_with_walk
        description: "Trip duration including walk time based on route_id"
        type: integer
        tests:
          - not_null
      
      - name: next_route_bus_waiting_time
        description: "Time to wait for next bus on the same route in minutes"
        type: integer
      
      - name: next_bus_waiting_time
        description: "Time to wait for next bus on any route in minutes"
        type: integer
      
      - name: day_of_timeslot
        description: "Day of the week (e.g., Monday, Tuesday)"
        type: string
        tests:
          - not_null
      
      - name: time_slot
        description: "Time slot classification (Start at 11, Start at 12, Other)"
        type: string
        tests:
          - not_null
      
      - name: weekday
        description: "Weekday number (1=Monday, 7=Sunday)"
        type: integer
        tests:
          - not_null