dbt_data_transform:
  target: dev
  outputs:
    dev:
      type: bigquery
      method: oauth
      project: "{{ env_var('GCP_PROJECT_ID') }}"
      dataset: "{{ env_var('GCP_DATASET_BIGQUERY') }}"
      job_execution_timeout_seconds: 300
      job_retries: 1
      priority: interactive
      threads: 1
