name: DBT Test

on:
  push:
    branches: [ main ]

jobs:
  dbt-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install uv
        uses: astral-sh/setup-uv@v5
        with:
          version: "0.7.12"

      - name: Install dependencies
        run: |
          uv sync
          uv venv

      - name: Run dbt test
        run: |
          uv run dbt test