version: 2

models:
  - name: stops_consolidated_dynamic_sources
    description: "Dynamically consolidated stops data from all stops_* tables"
    columns:
      - name: type
        description: "Type of the stop"
        type: string
        tests:
          - not_null
      
      - name: id
        description: "Unique identifier for the stop"
        type: string
        tests:
          - not_null
      
      - name: location_type
        description: "Type of location"
        type: integer
      
      - name: parent_station
        description: "Reference to parent station if this is a stop within a station"
        type: string
      
      - name: platform_code
        description: "Platform identifier for the stop"
        type: string
      
      - name: stop_code
        description: "Short text or number that identifies the location for riders"
        type: string
      
      - name: stop_id
        description: "Unique identifier for the stop"
        type: string
        tests:
          - not_null
      
      - name: stop_lat
        description: "Latitude of the stop location"
        type: float
      
      - name: stop_lon
        description: "Longitude of the stop location"
        type: float
      
      - name: stop_name
        description: "Name of the stop"
        type: string
        tests:
          - not_null
      
      - name: wheelchair_boarding
        description: "Indicates whether wheelchair boarding is possible (0=no info, 1=some vehicles, 2=no wheelchair boarding)"
        type: integer
      
      - name: api_date_ingestion
        description: "Date when the data was ingested from the API"
        type: date
      
      - name: source_table
        description: "Original table name where this record came from"
        type: string
        tests:
          - not_null
      
      - name: consolidated_at
        description: "Timestamp when this record was consolidated"
        type: timestamp
        tests:
          - not_null